In [1]:
import pandas as pd # 데이터 전처리
import numpy as np # 데이터 전처리
import matplotlib.pyplot as plt # 데이터 시각화
import itertools

In [31]:
train = pd.read_csv("../data/SecMeter_20191102.log")

In [33]:
train.tail(100000)

          20190801000000  H001  f2:42:2d:66:85:a6  0.07938499165314047
69020799  20190807201322  H002  90:09:94:24:f5:b4             0.104392
69020800  20190807201323  H002  90:09:94:24:f5:b4             0.098911
69020801  20190807201324  H002  90:09:94:24:f5:b4             0.099072
69020802  20190807201325  H002  90:09:94:24:f5:b4             0.102676
69020803  20190807201326  H002  90:09:94:24:f5:b4             0.096683
...                  ...   ...                ...                  ...
69120794  20190808235956  H002  90:09:94:24:f5:b4             0.096628
69120795  20190808235957  H002  90:09:94:24:f5:b4             0.092234
69120796  20190808235958  H002  90:09:94:24:f5:b4             0.098579
69120797  20190808235959  H002  90:09:94:24:f5:b4             0.095769
69120798  20190808240000  H002  90:09:94:24:f5:b4             0.091043

[100000 rows x 4 columns]

In [27]:
train.groupby(train.H001).sum()

      20190801000000  0.07690382160353954
H001
H001    1.081597e+20        445220.477098
H088    5.700777e+19        164630.798248
H089    1.081597e+20        520684.468843
H090    1.081597e+20        317348.956928
H091    1.081597e+20        546881.317145
H092    1.081597e+20        520684.630007
H093    1.081597e+20        445210.594173
H094    1.081597e+20        317346.929635
H095    1.081597e+20        494503.793910
H096    1.081597e+20        520695.297894
H097    1.081597e+20        494499.564659
H098    1.081597e+20        445216.783007
H099    1.081597e+20        494501.085918
H100    1.081597e+20        445219.017842

In [30]:
train.nunique()

20190801000000          5356862
H001                         14
f2:42:2d:66:85:a6            14
0.07690382160353954    72462654
dtype: int64